version: "3.9"
services:
  witness: &witness
    container_name: keriox-witness
    image: "ghcr.io/thclab/keriox-witness:0.5.0"
    restart: always
    networks:
      - dkms-network

  witness1:
    container_name: keriox-witness1
    <<: *witness
    ports:
      - "3232:3232"
    volumes:
      - type: bind
        source: ./config/witness1.yml
        target: /app/witness.yml

  witness2:
    container_name: keriox-witness2
    <<: *witness
    ports:
      - "3233:3233"
    volumes:
      - type: bind
        source: ./config/witness2.yml
        target: /app/witness.yml

  witness3:
    container_name: keriox-witness3
    <<: *witness
    ports:
      - "3234:3234"
    volumes:
      - type: bind
        source: ./config/witness3.yml
        target: /app/witness.yml

  watcher:
    container_name: keriox-watcher
    image: "ghcr.io/thclab/keriox-watcher:0.5.0"
    restart: always
    depends_on:
      - witness
      - witness2
      - witness3
    ports:
      - "3235:3235"
    volumes:
      - type: bind
        source: ./config/watcher.yml
        target: /app/watcher.yml
    networks:
      - dkms-network

  mesagkesto:
    container_name: mesagkesto
    image: "ghcr.io/thclab/mesagkesto:v0.1.2-beta.1"
    restart: always
    depends_on:
      - watcher
    ports:
      - "3236:3236"
    volumes:
      - type: bind
        source: ./config/messagebox.yml
        target: /app/messagebox.yml
    networks:
      - dkms-network

networks:
  dkms-network:
