witness:
  - eid: BDg1zxxf8u4Hx5IPraZzmStfSCZFZbDzMHjqVcFW5OfP  
    scheme: http
    url: http://172.17.0.1:3234/
watcher: 
  - eid: BF2t2NPc1bwptY1hYV0YCib1JjQ11k9jtuaZemecPF5b
    scheme: http
    url: http://172.17.0.1:3235/