db_path: "db/"
public_url: "http://localhost:3235/"
seed: "Alntkt3u6dDgiQxTATr01dy8M72uuaZEf9eTdM-70Gk8"
http_port: 3235
initial_oobis:
  - eid: "BDg1zxxf8u4Hx5IPraZzmStfSCZFZbDzMHjqVcFW5OfP"
    scheme: "http"
    url: "http://keriox-witness3:3234/"
  - eid: "BDg3H7Sr-eES0XWXiO8nvMxW6mD_1LxLeE1nuiZxhGp4"
    scheme: "http"
    url: "http://keriox-witness2:3233/"
  - eid: "BJq7UABlttINuWJh1Xl2lkqZG4NTdUdqnbFJDa6ZyxCC"
    scheme: "http"
    url: "http://keriox-witness1:3232/"
escrow_config:
  default_timeout: 60
