services:
  witness: &witness
    container_name: keriox-witness
    image: "ghcr.io/thclab/keriox-witness:latest"
    restart: always
    networks:
      - dkms-network

  witness1:
    container_name: keriox-witness1
    <<: *witness
    ports:
      - "3232:3232"
    volumes:
      - type: bind
        source: ./config/witness1.yml
        target: /app/witness.yml
      - witness1_db_data:/app/db

  witness2:
    container_name: keriox-witness2
    <<: *witness
    ports:
      - "3233:3233"
    volumes:
      - type: bind
        source: ./config/witness2.yml
        target: /app/witness.yml
      - witness2_db_data:/app/db/

  witness3:
    container_name: keriox-witness3
    <<: *witness
    ports:
      - "3234:3234"
    volumes:
      - type: bind
        source: ./config/witness3.yml
        target: /app/witness.yml
      - witness3_db_data:/app/db/

  watcher:
    container_name: keriox-watcher
    image: "ghcr.io/thclab/keriox-watcher:latest"
    restart: always
    depends_on:
      - witness
      - witness2
      - witness3
    ports:
      - "3235:3235"
    volumes:
      - type: bind
        source: ./config/watcher.yml
        target: /app/watcher.yml
      - watcher_db_data:/app/db/
    networks:
      - dkms-network

  mesagkesto:
    container_name: mesagkesto
    image: "ghcr.io/thclab/mesagkesto:latest"
    restart: always
    depends_on:
      - watcher
    ports:
      - "3236:3236"
    volumes:
      - type: bind
        source: ./config/messagebox.yml
        target: /app/messagebox.yml
    networks:
      - dkms-network

networks:
  dkms-network:

volumes:
  witness1_db_data:
  witness2_db_data:
  witness3_db_data:
  watcher_db_data:
